### ISSUE TITLE
How to save FSM state?

### ISSUE THREAD

**Issue by Fomikadze** [open-jumpco/kfsm#9]
Hi!
I have played with PayingTurnstile example. And the main problem. After I restore the process from storage, I have a mistake "stack is empty". It comes from StateMap. And I don't understand how to push the right step.

Is there any way to save FSM state for processes that live for a long time?

**Comment by corneil** [comment]
You can rely on 2 strategies:

* Your context provides enough information to determine the state using `initialState`  as seen here [https://open.jumpco.io/projects/kfsm/index.html#packaged-definition-and-execution](https://open.jumpco.io/projects/kfsm/index.html#packaged-definition-and-execution)
* You expose `externalState()` of the FSM so that it can be saved and provided to FSM as 2nd parameter when creating the instance from a definition.

This example was updated to illustrate the complete externalization of state of FSM and Content.

[PayingTurnstileFsmTests](https://github.com/open-jumpco/kfsm/blob/master/src/jvmTest/kotlin/PayingTurnstileFsmTests.kt)

**Comment by Fomikadze** [comment]
@corneil thanks!
I had understood my mistake. I was saving not full ExternalState, but only the first state.
But also I had solved the problem in the sample of PayingTurnstileFSM, https://open.jumpco.io/projects/kfsm/index.html#packaged-definition-and-execution
If we pass value larger than requiredCoins, the PayingTurnstileFSM will stock in the current sate. 
```
onEventPush(PayingTurnstileEvents.COIN, "coins", PayingTurnstileStates.COINS) { value ->
    require(value != null) { "argument required for COIN" }
    coin(value)
    unlock()
    reset()
}
```
If we remove unlock() and reset() steps. Then everything will work fine. And now when we pass  value larger than requiredCoins, we will get into the right automaticPop of the "conis" StateMap:
```
automaticPop(PayingTurnstileStates.UNLOCKED, guard = { coins > requiredCoins }) {
    println("automaticPop:returnCoin")
    returnCoin(coins - requiredCoins)
    unlock()
    reset()
}
```

**Comment by corneil** [comment]
The change I made saves the number of coins and the locked state as well. That way it works when saving and restoring the state of FSM and Context. unlock and reset remains to serve their purpose.
